
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kingsley
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: petitepatte
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  nextjs:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: kingsley
      DB_PASS: admin
      DB_NAME: petitepatte
      DATABASE_URL: postgres://kingsley:admin@postgres:5432/petitepatte
      DNS: https://petitepattestyle.com
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - nextjs


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
    expose:
      - "5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

